# Generated by Django 2.2.6 on 2020-02-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='gambar',
        ),
    ]
