# Generated by Django 2.2.6 on 2020-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gambar',
            field=models.ImageField(default='default.jpg', upload_to='article/'),
        ),
    ]
