# Generated by Django 2.2.6 on 2020-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200220_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.TextField(),
        ),
    ]
